version: "3.8"

services:
  web:
    image: php:7.4-apache
    container_name: php_apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    entrypoint: ["/var/www/html/init.sh"]
    networks:
      my_network:
        ipv4_address: 10.10.0.10

networks:
  my_network:
    external: true
